const FETCH_ALL_PLANS = "FETCH_ALL_PLANS";
const ADD_PLAN = "ADD_PLAN";
const UPDATE_PLAN = "UPDATE_PLAN";
const DELETE_PLAN = "DELETE_PLAN";
const EDIT_PLAN = "EDIT_PLAN";
const SHOWLOADER = "SHOWLOADER";
const HIDELOADER = "HIDELOADER";



export {
    FETCH_ALL_PLANS,
    ADD_PLAN,
    UPDATE_PLAN,
    DELETE_PLAN,
    EDIT_PLAN,
    SHOWLOADER,
    HIDELOADER,
}

